#!/usr/bin/env python3
"""Build the site from the per-issue sources.

Each issue lives in its own folder (issues/01/, issues/02/, ...) with two
hand-edited files: issue.json (structured data) and stories.html (prose).
This script renders issues/NN/index.html from them with templates/issue.html,
then generates index.html (latest issue), archive.html and feed.xml.
Run it after adding or changing an issue:

    python3 scripts/build.py          # write the generated files
    python3 scripts/build.py --check  # exit 1 if they are out of date (CI)

Standard library only, so it runs anywhere Python 3.8+ is installed.
"""
import html
import re
import sys
from datetime import datetime, timezone
from email.utils import format_datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from render_issue import render as render_issue  # noqa: E402

SITE_URL = "https://wealth-tax-watch.vercel.app"
SITE_TITLE = "Wealth Tax Watch"
SITE_DESC = ("A personal tracker of wealth tax developments around the world: proposals, "
             "public opinion and international tax cooperation, with a new issue every "
             "two weeks.")

ROOT = Path(__file__).resolve().parent.parent
GENERATED = "<!-- Generated by scripts/build.py from {src}. Edit the source, then rerun the script. -->\n"


def meta(page, attr, name):
    m = re.search(r'<meta %s="%s" content="([^"]*)"' % (attr, re.escape(name)), page)
    if not m:
        sys.exit("missing <meta %s=\"%s\">" % (attr, name))
    return html.unescape(m.group(1))


def load_issues():
    issues = []
    for src in sorted((ROOT / "issues").glob("*/issue.json")):
        path = src.parent / "index.html"
        page = render_issue(src.parent, SITE_URL)
        slug = path.parent.name
        issues.append({
            "slug": slug,
            "path": path,
            "page": page,
            "title": meta(page, "property", "og:title"),
            "description": meta(page, "name", "description"),
            "published": meta(page, "property", "article:published_time"),
            "url": "%s/issues/%s/" % (SITE_URL, slug),
        })
    if not issues:
        sys.exit("no issues found under issues/")
    return issues


def render_index(latest):
    # The root page is a copy of the latest issue, with links that climb out of
    # issues/NN/ rewritten to work from the site root. Its canonical URL stays
    # pointed at the issue's permanent address.
    page = latest["page"].replace('href="../../', 'href="').replace('src="../../', 'src="')
    return re.sub(r"<!-- Generated by scripts/build.py[^\n]*-->\n", GENERATED.format(
        src="issues/%s/issue.json and stories.html" % latest["slug"]).replace("\\", "\\\\"), page, count=1)


def render_archive(issues):
    rows = "\n".join(
        '      <li><a href="issues/{slug}/"><span class="no">No. {slug}</span>'
        '<span class="t">{title}</span><time datetime="{pub}">{pub_h}</time>'
        '<span class="d">{desc}</span></a></li>'.format(
            slug=i["slug"],
            title=html.escape(i["title"]),
            pub=i["published"],
            pub_h=datetime.strptime(i["published"], "%Y-%m-%d").strftime("%B %-d, %Y"),
            desc=html.escape(i["description"]),
        )
        for i in reversed(issues)
    )
    return """<!DOCTYPE html>
""" + GENERATED.format(src="issues/*/issue.json") + """<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Wealth Tax Watch · All issues</title>
<meta name="description" content="{desc}">
<link rel="canonical" href="{site}/archive.html">
<link rel="alternate" type="application/rss+xml" title="Wealth Tax Watch" href="{site}/feed.xml">
<meta property="og:title" content="Wealth Tax Watch · All issues">
<meta property="og:description" content="{desc}">
<meta property="og:image" content="{site}/assets/og-image.png">
<meta name="twitter:card" content="summary_large_image">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Anton&display=swap" rel="stylesheet">
<style>
:root{{ --bg:#F1EEE6; --paper:#FDFCF8; --ink:#141A2B; --muted:#5E6474; --hair:#D6D1C4; --pink-text:#C8203F; --blue:#2B46EE; }}
@media (prefers-color-scheme: dark){{ :root{{ --bg:#12151F; --paper:#1B2030; --ink:#EEEAE0; --muted:#A3A8B6; --hair:#333A4D; --pink-text:#FF4F6B; --blue:#7E92FF; }} }}
*{{ box-sizing:border-box; }}
body{{ margin:0; background:var(--bg); color:var(--ink); font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-size:17px; line-height:1.55; }}
.wrap{{ max-width:860px; margin:0 auto; padding:56px 24px 64px; }}
a{{ color:inherit; }}
:focus-visible{{ outline:3px solid var(--blue); outline-offset:3px; border-radius:4px; }}
.eyebrow{{ color:var(--blue); font-weight:800; font-size:13px; letter-spacing:.12em; margin:0 0 12px; }}
h1{{ font-family:'Anton',Impact,'Arial Narrow',sans-serif; font-weight:400; font-size:clamp(34px,6vw,52px); letter-spacing:.005em; line-height:1.05; margin:0 0 14px; }}
h1 em{{ color:var(--pink-text); font-style:italic; }}
p.lede{{ color:var(--muted); margin:0 0 32px; max-width:60ch; }}
ol{{ list-style:none; margin:0; padding:0; border-top:3px solid var(--ink); }}
li a{{ display:grid; grid-template-columns:90px 1fr auto; gap:6px 20px; padding:20px 0; border-bottom:1px solid var(--hair); text-decoration:none; }}
li a:hover .t{{ text-decoration:underline; text-decoration-thickness:2px; text-underline-offset:3px; }}
.no{{ font-weight:800; font-size:13px; letter-spacing:.08em; color:var(--pink-text); padding-top:4px; }}
.t{{ font-family:'Anton',Impact,'Arial Narrow',sans-serif; font-weight:400; font-size:21px; line-height:1.2; letter-spacing:.01em; }}
time{{ font-weight:700; font-size:14px; color:var(--muted); white-space:nowrap; padding-top:4px; }}
.d{{ grid-column:2 / -1; color:var(--muted); font-size:15px; }}
footer{{ margin-top:40px; font-size:14px; color:var(--muted); }}
@media (max-width:560px){{ li a{{ grid-template-columns:1fr; }} .d{{ grid-column:auto; }} }}
</style>
</head>
<body>
<main class="wrap">
  <p class="eyebrow">BIWEEKLY BRIEFING</p>
  <h1>Wealth Tax <em>Watch</em>: all issues</h1>
  <p class="lede">{desc}</p>
  <ol>
{rows}
  </ol>
  <footer><a href="./">Latest issue</a> · <a href="feed.xml">RSS feed</a></footer>
</main>
</body>
</html>
""".format(site=SITE_URL, desc=html.escape(SITE_DESC), rows=rows)


def render_feed(issues):
    def pubdate(i):
        d = datetime.strptime(i["published"], "%Y-%m-%d").replace(hour=12, tzinfo=timezone.utc)
        return format_datetime(d)

    items = "\n".join(
        "    <item>\n"
        "      <title>{t}</title>\n"
        "      <link>{u}</link>\n"
        "      <guid isPermaLink=\"true\">{u}</guid>\n"
        "      <pubDate>{d}</pubDate>\n"
        "      <description>{desc}</description>\n"
        "    </item>".format(t=html.escape(i["title"]), u=i["url"], d=pubdate(i),
                             desc=html.escape(i["description"]))
        for i in reversed(issues)
    )
    return """<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>{title}</title>
    <link>{site}/</link>
    <atom:link href="{site}/feed.xml" rel="self" type="application/rss+xml"/>
    <description>{desc}</description>
    <language>en</language>
    <lastBuildDate>{last}</lastBuildDate>
{items}
  </channel>
</rss>
""".format(title=SITE_TITLE, site=SITE_URL, desc=html.escape(SITE_DESC),
           last=pubdate(issues[-1]), items=items)


def main():
    check = "--check" in sys.argv[1:]
    issues = load_issues()
    outputs = {"issues/%s/index.html" % i["slug"]: i["page"] for i in issues}
    outputs.update({
        "index.html": render_index(issues[-1]),
        "archive.html": render_archive(issues),
        "feed.xml": render_feed(issues),
    })
    stale = []
    for name, content in outputs.items():
        path = ROOT / name
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if check:
            stale.append(name)
        else:
            path.write_text(content, encoding="utf-8")
            print("wrote", name)
    if stale:
        sys.exit("out of date: %s. Run: python3 scripts/build.py" % ", ".join(stale))
    if check:
        print("generated files are up to date")


if __name__ == "__main__":
    main()
